version: "3"
services:
  server:
    image: gocd/gocd-server:v19.8.0
    restart: on-failure
    volumes:
      - ./home:/home/go:rw
      - ./server:/godata:rw
    ports:
      - "8153:8153"
      - "8154:8154"

  agent:
    image: gocd/gocd-agent-ubuntu-16.04:v19.8.0
    environment:
      GO_SERVER_URL: http://server:8153/go
    restart: on-failure
    volumes:
      - ./home:/home/go:rw
      - ./agent:/godata:rw
